DOMAIN = "azure-blob-sync"
CONF_CONNECTION_STRING = "connection_string"
CONF_CONTAINER_NAME = "container_name"
CONF_LOCAL_FOLDER = "local_folder"
CONF_BLOB_FOLDER = "blob_folder"
CONF_SYNC_MODES = "sync_modes"
CONF_SYNC_INTERVAL = "sync_interval"
CONF_TRIGGER_ENTITY = "trigger_entity"
CONF_TRIGGER_STATE = "trigger_state"

SYNC_MODE_MANUAL = "manual"
SYNC_MODE_SCHEDULE = "schedule"
SYNC_MODE_EVENT = "event"
